app = "zkcargopass-backend"
primary_region = "sin"  # Singapore region, change as needed

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "3001"
  NODE_ENV = "production"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  interval = "30s"
  timeout = "5s"
  grace_period = "10s"
  method = "GET"
  path = "/health"
  protocol = "http"
  tls_skip_verify = false

[mounts]
  source = "zkcargopass_data"
  destination = "/data"

[metrics]
  port = 3001
  path = "/metrics" 